FROM php:8.1.5-apache
RUN apt-get update && apt-get upgrade -y 
RUN docker-php-ext-install mysqli pdo pdo_mysql
RUN if command -v a2enmod >/dev/null 2>&1; then \
    a2enmod rewrite headers \
    ;fi
EXPOSE 80


